---
- name: Install nginx
  sudo: yes
  apt: pkg=nginx state=present update_cache=yes

- name: Add nginx config
  sudo: yes
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root
  tags:
    - Restart nginx

- name: Add nginx mime types
  sudo: yes
  copy: src=mime.types dest=/etc/nginx/mime.types owner=root group=root

- name: Add Site Config
  sudo: yes
  template: src=wpkit.dev.conf.j2 dest=/etc/nginx/sites-available/wpkit.conf owner=root group=root

- name: Enable Site Config
  sudo: yes
  file: src=/etc/nginx/sites-available/wpkit.conf dest=/etc/nginx/sites-enabled/wpkit.conf state=link
  register: config_added

- name: Reload nginx
  sudo: yes
  when: config_added.changed == True
  service: name=nginx state=reloaded
